/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 23 21:45:52 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TrazAquiView_ESTest extends TrazAquiView_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TrazAquiView trazAquiView0 = new TrazAquiView();
      trazAquiView0.nome();
      trazAquiView0.nif();
      TrazAquiView.showMenuVoluntario();
      trazAquiView0.loadMenu();
      trazAquiView0.latitude();
      trazAquiView0.headRegistoUser();
      TrazAquiView.showMenuLoja();
      trazAquiView0.encomendas_medicas();
      trazAquiView0.password();
      trazAquiView0.preenchimentoObrg();
      trazAquiView0.headLoginEmpresa();
      trazAquiView0.longitude();
      trazAquiView0.password();
      trazAquiView0.produto();
      trazAquiView0.password();
      trazAquiView0.nr_min_encomendas();
      trazAquiView0.loadMenu();
      trazAquiView0.preenchimentoObrg();
      trazAquiView0.headRegistoLoja();
      TrazAquiView.showMenuTransportes();
      trazAquiView0.headNovaEncomenda();
      trazAquiView0.headRegistoUser();
      trazAquiView0.email();
      trazAquiView0.tempo_espera();
      trazAquiView0.headNovaEncomenda();
      trazAquiView0.preenchimentoObrg();
      trazAquiView0.headRegistoUser();
      trazAquiView0.headLoginLoja();
      TrazAquiView.showMenuVoluntario();
      TrazAquiView.showMenuVoluntario();
      trazAquiView0.local();
      TrazAquiView.showMenuTransportes();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TrazAquiView.showMenuVoluntario();
      TrazAquiView trazAquiView0 = new TrazAquiView();
      trazAquiView0.showMenuLogin();
      trazAquiView0.showMenuRegisto();
      trazAquiView0.headLoginUser();
      trazAquiView0.longitude();
      trazAquiView0.headRegistoUser();
      TrazAquiView.showMenuUser();
      trazAquiView0.encomendas_medicas();
      trazAquiView0.nr_min_encomendas();
      trazAquiView0.tempo_espera();
      trazAquiView0.preenchimentoObrg();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TrazAquiView trazAquiView0 = new TrazAquiView();
      trazAquiView0.headLoginLoja();
      trazAquiView0.headRegistoVoluntario();
      trazAquiView0.printHeader();
      trazAquiView0.nif();
      trazAquiView0.tempo_espera();
      trazAquiView0.custo_km();
      trazAquiView0.nome();
      trazAquiView0.headRegistoLoja();
      trazAquiView0.headRegistoEmpresa();
      trazAquiView0.headLoginVoluntario();
      trazAquiView0.showMenuLogin();
      trazAquiView0.nif();
      trazAquiView0.nome();
      trazAquiView0.tempo_espera();
      trazAquiView0.password();
      trazAquiView0.tempo_espera();
      trazAquiView0.latitude();
      trazAquiView0.raio_acao();
      trazAquiView0.latitude();
      trazAquiView0.loadMenu();
      trazAquiView0.showMenuInicial();
      trazAquiView0.custo_km();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TrazAquiView trazAquiView0 = new TrazAquiView();
      trazAquiView0.headRegistoLoja();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TrazAquiView trazAquiView0 = new TrazAquiView();
      trazAquiView0.headLoginUser();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TrazAquiView trazAquiView0 = new TrazAquiView();
      trazAquiView0.showMenuLogin();
  }
}
